LEFT_MOTOR_PORT = 'A'
RIGHT_MOTOR_PORT = 'B'
BACK_MOTOR_PORT = 'F'
FRONT_MOTOR_PORT = 'D'
LEFT_COLOR_SENSOR_PORT = 'C'
RIGHT_COLOR_SENSOR_PORT = 'E'
WHEEL_DIAMETER = 55.5
AXLE_TRACK = 124
STRAIGHT_SPEED = 600
STRAIGHT_ACCELERATION = 400
TURN_RATE = 149
<<<<<<< Updated upstream
TURN_ACCELERATION = 500
=======
TURN_ACCELERATION = 100
>>>>>>> Stashed changes
